- backend/utils.py
- backend/validators.py
This PR fixes the required fields: default fields are no longer required during validation.
> Required fields fix

- backend/backend_blueprint.py
- backend/models.py
- Uses flask_* instead of flask.et
> Update deprecated imports

- backend/models.py
New preflight OPTIONS have been added
> New preflight OPTIONS

- backend/backend_blueprint.py
- backend/models.py
Change **deprecated** use from `flask.ext`
> Fix imports flask.ext deprecations

- backend/models.py
- backend/pool.py
- backend/utils.py
> Fix Py3 issues

- backend/__init__.py
- backend/backend_blueprint.py
- backend/models.py
> Fix imports using package

- backend/utils.py
Use a `SimpleCache` to improve speed
> Speed improvements using cache

- backend/utils.py
Add a missing timeout when setting a cache
> Missing cache timeout

- backend/validators.py
Update to new Cerberus API http://docs.python-cerberus.org/en/stable/upgrading.html#data-types
> Update to new Cerberus API

- backend/utils.py
Only make the `write` for the fields which have diffent values from stored values
> Smart update (only if it's different)

- backend/utils.py
Add support for py3 items() and list(keys())
> Add support for py3 items() and list(keys())

- backend/utils.py
Add support for `fields.reference` with a simple `regex`
> Support for reference fields

- backend/models.py
- Add docstrings
- Comment request arguments
> Improve code documentation

- README.rst
- backend/models.py
*Refactor of the model.py code to don't use id as a variable. Changed by obj_id.
*Added docstrings to the file model.py.
*Updated the readme file.
*Features not modified.
> Code refactor and update doc

- README.rst
* Improved the documentation of the demo URL of the method "GET /api/<model>".
> Improved the API documentation.

- backend/models.py
> Fix docstrings

- backend/utils.py
- Manages binary field as string field
> Add support for binary field

- backend/models.py
It enhances a Model to be able to pass the SQL order criteria using `order` parameter while searching.
> Add order param to Model

- backend/pool.py
- requirements.txt
- Checks if the connection paramenters are byte of string to encode it to utf-8
- Adds `six` as requirement
> Improve python2-3 compatibility

- backend/models.py
- Use read with domain http://erppeek.readthedocs.io/en/latest/api.html?highlight=read#erppeek.Client.read
> Millorar el rendiment del read usant read amb domain

- backend/backend_blueprint.py
- backend/pool.py
With this commit works with python2/3
> Fix encode/decode utf-8

- backend/utils.py
One block was two identations inside
> Fix identation

- backend/utils.py
Before this change if you want to set an id you should post:
```json
{
"field_id": {"id": 45}
}
```
Now it's possible to do directly:
```json
{
"field_id": 45
}
```
> Allow to Post with id directly if is a many2one

- backend/models.py
- Pass the ids instead of empty domain
> Improve compatibility with Erppeek >1.7

- backend/pool.py
Allow connections to a ERP server throught https-xmlrpc protocol
> IMP Allow https connection through erppeek

- backend/models.py
- backend/pool.py
##OBJECTIVES
To solve related issues:
#48 
#49
> Solve Request Problems
